# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sahil Raja
title: Jr Software Engineer
email: sahilraja100@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: sahilraja0
github_username:  Sahil590
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: sahil_raja

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sahil and I'm a Software Devloper for Imperial college currently. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Full stack website for trading and informing platform about E-waste
       # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
        - This was my second year project which involved working as a team to develop a full stack web 
          application. 
        - This project was creating an E-Waste trading web applet where users can trade and learn about Ewaste. This is one of my major passions to reduce E-Waste and teach others about it. 
        - We were tasked to work as a group to develop a full stack application using a combination of 
        techniques such as Java spring boot, REST APIs, SQL and React. 
        - We used SCRUM methodology to help plan the project and assign roles to the group. 
        - I learned how to keep deadlines and used github to track other peoples work as we were implementing all the features together 
        - I learned to effectively carry out data analysis by using tools such as SPSS and SQL this was used  to analyse tweets for certain information. 
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Imperial College London
        link: Imperial.ac.uk
        # link_text: boringcompany.com
        sub_title: Jr Sofware Engineer
        caption: January 2024 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          I have been working at Imperial College for the past 3 years and have been working on a variety of projects. I have been working on a variety of projects such as the *Imperial College London Website* and the *Imperial College London App*.

          I have been working with a variety of technologies such as *React*, *Node.js* and *MongoDB*.
    content:
      - layout: left
        title: Imperial College London
        link: Imperial.ac.uk
        sub_title: 1st line support analyst
        caption: December 2022 - January 2024
        description: |
        - Provide first-line technical support to students, faculty, and staff, ensuring timely resolution of IT-related issues. 
        - Troubleshoot hardware and software problems, both remotely and in-person, to maintain a seamless computing environment. 
        - Maintain accurate service requests, resolutions, and equipment inventory records to track and improve service quality. 
        - Collaborate with second-line support teams to escalate complex issues and ensure effective problem resolution. 
        - Knowledge of a broad range of ICT technologies to provide 1st line support; Bomgar, Mesh commander, PowerShell, HDB, Jamf, SOV, SCCM, VM, and other tools. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Brunel University
        caption: 2019 - 2022
        sub_title: BSc Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
